version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  dev:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build: .
      # context: .
      # dockerfile: .devcontainer/Dockerfile
    environment:
      # # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_PYTHON_LOG_CORRELATION: "true"    
      REDIS_URL: "redis://redis:6379"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/usr/src/app
      # - ../.devcontainer/launch.json:/app/.vscode/launch.json:ro

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    # Removed from command since we arent using django but keeping it around for notes

    command: >
      sh -c "
      echo 'DevContainer: Waiting for Redis...' &&
      while ! nc -z redis 6379; do sleep 1; done &&
      echo 'DevContainer Ready. Use VS Code Run & Debug to start.' &&
      sleep infinity
      "
